- name: docker-machine-config
  hosts: docker-machine
  become: 'yes'
  become_user: 'docker-admin'
  tasks:
    - name: copy the docker file
      copy: src=Dockerfile dest=./app-files

    - name: copy the JfrogArtifactory Connection Script
      copy: src=jfrog-server-conn.sh dest=./app-files

    - name: change the execuatble permissions of the JfrogConn Script
      shell: chmod +x ./app-files/jfrog-server-conn.sh

    - name: change the executable permissions of the Dockerfile
      shell: chmod +x ./app-files/Dockerfile

    - name: execute the JfrogArtifactory conn Script
      shell: sh ./app-files/jfrog-server-conn.sh

    - name: docker image building
      shell: echo admin | sudo -S docker build ./app-files/Dockerfile --tag narsi1839/weshopify-7pm-app .

    - name: push the image to the Container Registry(CR)
      shell: echo admin | sudo -S docker push narsi1839/weshopify-7pm-app
    
    - name: remove the local image
      shell: echo admin | sudo -S docker rmi -f narsi1839/weshopify-7pm-app
